apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: my-frontend-app
        image: public.ecr.aws/a5z6u3o2/react-cicd:10
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_BASE_URL
            value: http://backend-service.default.svc.cluster.local:8080