db_name           = "mydb"
identifier        = "nimbus-database"
engine            = "postgres"
engine_version    = "15.5"
instance_class    = "db.t3.micro"
username          = "test"
password          = "password"
availability_zone = "eu-west-2a"
